=== ShartepStudy/XML/ClassWork/17.01.14/notebook.dtd
<!ELEMENT notebook (person+)>
<!ELEMENT person (name, surname, phone+, email*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT br EMPTY>
<!ELEMENT someelement (name, (phone | email))>
<!ELEMENT someelement1 (#PCDATA | br)*>

<!ATTLIST phone 
  citycode CDATA #REQUIRED
  attr1 (aaa | bbb | ccc) #IMPLIED 
  attr2 CDATA #FIXED "qqqq"
>

<!ENTITY author "tratatata">

=== ShartepStudy/XML/ClassWork/17.01.14/notebook.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE notebook SYSTEM "./notebook.dtd">
<notebook>
  <person>
    <name>Vasya</name>
    <surename>Vasilev</surename>
    <phone citycode="380482">23-56-87</phone>
    <email>abc@gmail.com</email>
  </person>
  <person>
    <name>Olya</name>
    <surename>Vasileva &author;</surename>
    <phone>23-56-87</phone>
    <email>abc@gmail.com</email>
  </person>
</notebook>
